name: travel_diaries
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.0-142.0.dev <3.0.0"

dependencies:
  # avatar_view: ^1.0.1
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  get: 4.5.1
  get_storage: ^2.0.3
  http: ^0.13.4
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  google_sign_in: ^5.2.1
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  flutter_scroll_to_top: ^2.1.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - images/

fonts:
  - family: Noto_Sans
    fonts:
      - asset: assets/fonts/NotoSans-Bold.ttf
        style: bold
      - asset: assets/fonts/NotoSans-BoldItalic.ttf
        style: bolditalic
      - asset: assets/fonts/NotoSans-Italic.ttf
        style: italic
      - asset: assets/fonts/NotoSans-Regular.ttf
        style: regular
